name: dashboard
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-283.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.6
  flutter_launcher_icons: ^0.10.0
  font_awesome_flutter: ^10.2.1
  ionicons: ^0.2.1
  carbon_icons: ^0.0.1
  get: ^4.6.5
  http: ^0.13.5
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  splashscreen: ^1.3.5
  sizer: ^2.0.15
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  provider: ^6.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700