name: dashboard
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-283.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  ionicons: ^0.2.1
  flutter_svg: ^1.1.5
  get: ^4.6.5
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: ^0.10.0
  page_transition: ^2.0.9
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700